#cloud-config
 
users:  
  - default 
  - name: rancher    
    gecos: rancher    
    primary_group: rancher    
    sudo: ALL=(ALL) NOPASSWD:ALL    
    groups: users, admin
    lock_passwd: false    
    ssh_authorized_keys:
      - ${public_key}

runcmd:
  - sudo systemctl disable --now firewalld
  - \curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=${k3s_version} K3S_KUBECONFIG_MODE=0644 INSTALL_K3S_EXEC="server --node-external-ip $(curl http://169.254.169.254/latest/meta-data/public-ipv4) --node-ip $(curl http://169.254.169.254/latest/meta-data/local-ipv4) --tls-san $(curl http://169.254.169.254/latest/meta-data/public-ipv4).nip.io" sh -s -
  - sudo sed "s/127.0.0.1/$(curl http://169.254.169.254/latest/meta-data/public-ipv4)/g" /etc/rancher/k3s/k3s.yaml

final_message: "The system is finally up, after $UPTIME seconds"
