#cloud-config
 
 users:  
  - default 
  - name: rancher    
    gecos: rancher    
    primary_group: rancher    
    sudo: ALL=(ALL) NOPASSWD:ALL    
    groups: users, admin
    lock_passwd: false    
    ssh_authorized_keys:
      - ${public_key}

package_update: true

runcmd:
  - sudo systemctl disable --now firewalld
  - TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
  - PUBLICIP=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/public-ipv4)
  - PRIVATEIP=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/local-ipv4)
  - curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=${k3s_version} K3S_KUBECONFIG_MODE=0644 INSTALL_K3S_EXEC=\"server --node-external-ip $PUBLICIP --node-ip $PRIVATEIP --tls-san $PUBLICIP.nip.io\" sh -s -
  - sudo sed \"s/127.0.0.1/$PUBLICIP/g\" /etc/rancher/k3s/k3s.yaml
  - sudo zypper up -n -q
