#cloud-config

script: |
  <powershell>
  Start-Transcript -Path "C:\UserData.log" -Append
  Stop-Service docker
  Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
  Start-Service sshd
  Set-Service -Name sshd -StartupType 'Automatic'
  ${cluster_registration}
  </powershell>
